# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "14"
    - nodejs_version: "16"

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g pnpm
  - pnpm i

test_script:
  # Output useful info for debugging.
  - node --version
  - pnpm --version
  # run tests
  - pnpm test

build: off
